export const CONFIG = {
  MAX_AMOUNT: 5000000,
  MIN_AMOUNT: 100,
  CURRENCY: 'NGN',
  KOBO_MULTIPLIER: 100,
  TRANSFER_TIMEOUT: 20000,
  DB_TIMEOUT: 5000,
  BATCH_SIZE: 25,
  PROCESSING_INTERVAL: 2000,
  MAX_RETRY_DELAY: 300,
} as const;

export const JOB_TYPES = {
  EMAIL_NOTIFICATION: 'EMAIL_NOTIFICATION',
  TRANSACTION_HISTORY: 'TRANSACTION_HISTORY',
  REVENUE_UPDATE: 'REVENUE_UPDATE',
  RESERVED_ACCOUNT_CREATION: 'RESERVED_ACCOUNT_CREATION',
  PUSH_NOTIFICATION: 'PUSH_NOTIFICATION',
} as const;

export type JobType = (typeof JOB_TYPES)[keyof typeof JOB_TYPES];

export const JOB_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const;

export type JobStatus = (typeof JOB_STATUS)[keyof typeof JOB_STATUS];
